# Generated by Django 5.2.6 on 2025-10-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('member', 'Member')], max_length=50),
        ),
    ]
