# Generated by Django 5.2.6 on 2025-10-13 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KirchaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('Half Kircha', 'Half Kircha'), ('Full Kircha', 'Full Kircha')], max_length=50)),
                ('max_members', models.IntegerField()),
                ('group_name', models.CharField(blank=True, max_length=50, null=True)),
                ('slaughter_date', models.DateField()),
                ('slaughter_time', models.TimeField()),
                ('slaughter_method', models.CharField(choices=[('self-slaughter', 'Self Slaughter'), ('company-managed', 'Company Managed')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kircha_group', to='livestock.livestock')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_kircha_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_full_name', models.CharField(max_length=50)),
                ('member_phone_number', models.CharField(max_length=50)),
                ('member_delivery_address', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='kirchagroups.kirchagroup')),
            ],
        ),
    ]
