# Generated by Django 5.2.6 on 2025-10-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirchagroups', '0002_groupmember_invited_by_groupmember_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirchagroup',
            name='price_full',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='kirchagroup',
            name='price_half',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
