# Generated by Django 5.2.6 on 2025-10-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestock',
            name='farmer',
        ),
    ]
