# Generated by Django 5.2.6 on 2025-10-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_remove_livestock_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livestock_images/'),
        ),
    ]
